### ISSUE TITLE
Convert to Vite.js

### ISSUE THREAD

**Issue by squidco** [SquidDOTjpeg/TGBL#91]
Create react app is no longer supported and hasn't been for a long time so it is time to convert. Time to find a conversion guide.

**Comment by mohamed-ali-halloul** [comment]
Hello can i take this issue and do it? thank you

**Comment by squidco** [comment]
> Hello can i take this issue and do it? thank you

Hey Mohomed, we actually have converted to Vite and moved on from this issue just haven't closed it out. Sorry for the confusion.
